# Generated by Django 6.0.4 on 2026-04-08 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('categoria', models.CharField(choices=[('servicios', 'Servicios Básicos (Luz/Agua)'), ('mantenimiento', 'Mantenimiento y Reparaciones'), ('sueldos', 'Sueldos y Previsión'), ('seguridad', 'Seguridad'), ('otros', 'Otros Gastos')], default='otros', max_length=20)),
                ('fecha_gasto', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
