# Generated by Django 6.0.4 on 2026-04-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('tipo', models.CharField(choices=[('propietario', 'Propietario'), ('arrendatario', 'Arrendatario')], default='propietario', max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('departamento', models.CharField(max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('servicios', 'Servicios Básicos'), ('mantenimiento', 'Mantenimiento'), ('sueldos', 'Sueldos'), ('seguridad', 'Seguridad'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
