# Generated by Django 6.0.4 on 2026-04-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_residente_alter_gasto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='torre',
            field=models.CharField(choices=[('A', 'Torre A'), ('B', 'Torre B')], default='A', max_length=10),
        ),
    ]
