# Generated by Django 6.0.3 on 2026-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-mes_correspondiente']},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='estado',
        ),
        migrations.AddField(
            model_name='pago',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
