# Generated by Django 6.0.3 on 2026-04-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_pago_options_remove_pago_estado_pago_notas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-mes_correspondiente'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
